--CREATE TABLESPACE EMPRESAGIIC14 DATAFILE 'C:\APP\DAVID2\ORADATA\TEST\EMPRESAGIIC14' SIZE 5M AUTOEXTEND OFF;
--select * from v$services;
--show con_name;
--alter session set container=pdbtest;
CREATE TABLESPACE EMPRESAGIIC14 DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\EMPRESAGIIC14.DBF' SIZE 5M AUTOEXTEND OFF;

CREATE USER GIIC14 IDENTIFIED BY GIIC14 DEFAULT TABLESPACE EMPRESAGIIC14 TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON EMPRESAGIIC14;

GRANT CREATE SESSION, CREATE TABLE, DELETE ANY TABLE, SELECT ANY
DICTIONARY, CREATE ANY SEQUENCE TO GIIC14;

select * from all_users;
select * from user_users;